{{- if (not .Values.configExistingSecret) }}
{{- $cfg := deepCopy .Values.config }}
{{- $dburi := default "" (index $cfg "db-uri") }}
{{- if and .Values.postgresql.enabled (eq $dburi "") }}
  {{- $user := default "" .Values.postgresql.global.postgresql.auth.username }}
  {{- $pass := default "" .Values.postgresql.global.postgresql.auth.password }}
  {{- $db := default "" .Values.postgresql.global.postgresql.auth.database }}
  {{- $port := default 5432 .Values.postgresql.global.postgresql.service.ports.postgresql }}
  {{- if or (eq $user "") (eq $pass "") (eq $db "") }}
    {{- fail "postgresql.enabled=true requires username/password/database (postgresql.global.postgresql.auth.*) or set config.db-uri manually" }}
  {{- end }}
  {{- $autoHost := printf "%s-postgresql" (include "opengist.fullname" .) }}
  {{- $autoUri := printf "postgres://%s:%s@%s:%d/%s" $user $pass $autoHost $port $db }}
  {{- $_ := set $cfg "db-uri" $autoUri }}
{{- end }}
{{- $replicas := int .Values.replicaCount }}
{{- $index := default "" (index $cfg "index") }}
{{- if and (gt $replicas 1) (or (eq $index "") (eq $index "bleve")) }}
  {{- fail "replicaCount>1 requires index set to 'meilisearch' (bleve not supported with multiple replicas)" }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opengist.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "opengist.labels" . | indent 4 }}
type: Opaque
stringData:
  config.yml: |-
    {{- $cfg | toYaml | nindent 4 }}
{{- end }}